# Generated by Django 6.0.5 on 2026-05-26 04:02

import ONLINE_QUIZ_APPLICATION.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import resultpageapp.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coursespageapp', '0001_initial'),
        ('quizpageapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('certificate_id', models.CharField(db_index=True, max_length=40, unique=True, verbose_name='Certificate ID')),
                ('issued_date', models.DateTimeField(auto_now_add=True, verbose_name='Issued date')),
                ('certificate_file', models.FileField(blank=True, upload_to=resultpageapp.models.certificate_file_path, validators=[ONLINE_QUIZ_APPLICATION.validators.validate_pdf_file_extension], verbose_name='Certificate PDF')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='coursespageapp.course', verbose_name='Course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL, verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Certificate',
                'verbose_name_plural': 'Certificates',
                'ordering': ['-issued_date'],
                'indexes': [models.Index(fields=['student', '-issued_date'], name='cert_student_issued_idx')],
                'constraints': [models.UniqueConstraint(fields=('student', 'course'), name='unique_certificate_per_student_course')],
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rank', models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='Rank')),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Score')),
                ('total_marks', models.PositiveIntegerField(default=0, verbose_name='Total marks')),
                ('percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Percentage')),
                ('remarks', models.CharField(blank=True, max_length=255, verbose_name='Remarks')),
                ('certificate_generated', models.BooleanField(default=False, verbose_name='Certificate generated')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Created at')),
                ('attempt', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='result', to='quizpageapp.quizattempt', verbose_name='Attempt')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='quizpageapp.quiz', verbose_name='Quiz')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to=settings.AUTH_USER_MODEL, verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Result',
                'verbose_name_plural': 'Results',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['student', '-created_at'], name='result_student_created_idx'), models.Index(fields=['quiz', 'rank'], name='result_quiz_rank_idx')],
            },
        ),
    ]
