# Generated by Django 6.0.5 on 2026-05-26 04:02

import ONLINE_QUIZ_APPLICATION.validators
import django.core.validators
import django.db.models.deletion
import quizpageapp.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coursespageapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='Question text')),
                ('question_image', models.ImageField(blank=True, upload_to=quizpageapp.models.question_image_path, validators=[ONLINE_QUIZ_APPLICATION.validators.validate_image_file_extension], verbose_name='Question image')),
                ('question_type', models.CharField(choices=[('single_choice', 'Single Choice'), ('multiple_choice', 'Multiple Choice'), ('true_false', 'True / False'), ('image_based', 'Image Based')], default='single_choice', max_length=25, verbose_name='Question type')),
                ('marks', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Marks')),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], db_index=True, default='beginner', max_length=20, verbose_name='Difficulty')),
                ('explanation', models.TextField(blank=True, verbose_name='Explanation')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Score')),
                ('total_correct', models.PositiveIntegerField(default=0, verbose_name='Total correct')),
                ('total_wrong', models.PositiveIntegerField(default=0, verbose_name='Total wrong')),
                ('percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Percentage')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Started at')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Submitted at')),
                ('time_taken', models.DurationField(blank=True, null=True, verbose_name='Time taken')),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], db_index=True, default='in_progress', max_length=20, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Quiz attempt',
                'verbose_name_plural': 'Quiz attempts',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(db_index=True, default=False, verbose_name='Correct')),
                ('answered_at', models.DateTimeField(auto_now_add=True, verbose_name='Answered at')),
            ],
            options={
                'verbose_name': 'Student answer',
                'verbose_name_plural': 'Student answers',
                'ordering': ['answered_at'],
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=500, verbose_name='Option text')),
                ('is_correct', models.BooleanField(db_index=True, default=False, verbose_name='Correct option')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='quizpageapp.question', verbose_name='Question')),
            ],
            options={
                'verbose_name': 'Option',
                'verbose_name_plural': 'Options',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quiz_title', models.CharField(default='Untitled Quiz', max_length=180, verbose_name='Quiz title')),
                ('quiz_description', models.TextField(blank=True, verbose_name='Quiz description')),
                ('total_questions', models.PositiveIntegerField(default=0, verbose_name='Total questions')),
                ('total_marks', models.PositiveIntegerField(default=0, verbose_name='Total marks')),
                ('passing_marks', models.PositiveIntegerField(default=0, verbose_name='Passing marks')),
                ('duration_minutes', models.PositiveIntegerField(default=30, verbose_name='Duration in minutes')),
                ('start_time', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Start time')),
                ('end_time', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='End time')),
                ('quiz_type', models.CharField(choices=[('practice', 'Practice'), ('mock_test', 'Mock Test'), ('scheduled', 'Scheduled'), ('random', 'Random')], db_index=True, default='practice', max_length=20, verbose_name='Quiz type')),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], db_index=True, default='beginner', max_length=20, verbose_name='Difficulty level')),
                ('randomize_questions', models.BooleanField(default=False, verbose_name='Randomize questions')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='coursespageapp.course', verbose_name='Course')),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quizzes',
                'ordering': ['-created_at'],
            },
        ),
    ]
