# Generated by Django 6.0.5 on 2026-05-26 04:02

import ONLINE_QUIZ_APPLICATION.validators
import coursespageapp.models
import django.core.validators
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(default='Untitled Course', max_length=180, verbose_name='Course title')),
                ('slug', models.SlugField(blank=True, max_length=210, unique=True, verbose_name='Slug')),
                ('course_description', models.TextField(default='', verbose_name='Course description')),
                ('short_description', models.CharField(blank=True, max_length=255, verbose_name='SEO short description')),
                ('meta_title', models.CharField(blank=True, max_length=180, verbose_name='SEO meta title')),
                ('meta_description', models.CharField(blank=True, max_length=255, verbose_name='SEO meta description')),
                ('thumbnail', models.ImageField(blank=True, upload_to=coursespageapp.models.course_thumbnail_path, validators=[ONLINE_QUIZ_APPLICATION.validators.validate_image_file_extension], verbose_name='Thumbnail')),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], db_index=True, default='beginner', max_length=20, verbose_name='Difficulty level')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='Course duration')),
                ('total_quizzes', models.PositiveIntegerField(default=0, verbose_name='Total quizzes')),
                ('total_students', models.PositiveIntegerField(default=0, verbose_name='Total students')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), ONLINE_QUIZ_APPLICATION.validators.validate_non_negative], verbose_name='Price')),
                ('is_published', models.BooleanField(db_index=True, default=False, verbose_name='Published')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=120, unique=True, verbose_name='Category name')),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True, verbose_name='Slug')),
                ('category_image', models.ImageField(blank=True, upload_to=coursespageapp.models.category_image_path, validators=[ONLINE_QUIZ_APPLICATION.validators.validate_image_file_extension], verbose_name='Category image')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Course category',
                'verbose_name_plural': 'Course categories',
                'ordering': ['category_name'],
            },
        ),
    ]
