# Generated by Django 6.0.5 on 2026-05-26 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Login time')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('user_agent', models.TextField(blank=True, verbose_name='User agent')),
                ('was_successful', models.BooleanField(default=True, verbose_name='Successful login')),
            ],
            options={
                'verbose_name': 'Login history',
                'verbose_name_plural': 'Login history',
                'ordering': ['-login_time'],
            },
        ),
    ]
