# Generated by Django 6.0.5 on 2026-05-26 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(max_length=200, verbose_name='Site title')),
                ('hero_title', models.CharField(max_length=255, verbose_name='Hero title')),
                ('hero_subtitle', models.TextField(verbose_name='Hero subtitle')),
                ('total_courses', models.PositiveIntegerField(default=0, verbose_name='Total courses')),
                ('total_quizzes', models.PositiveIntegerField(default=0, verbose_name='Total quizzes')),
                ('total_students', models.PositiveIntegerField(default=0, verbose_name='Total students')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Homepage content',
                'verbose_name_plural': 'Homepage content',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='Email')),
                ('subject', models.CharField(max_length=180, verbose_name='Subject')),
                ('message', models.TextField(verbose_name='Message')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'Contact feedback',
                'verbose_name_plural': 'Contact feedback',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', '-created_at'], name='feedback_email_created_idx')],
            },
        ),
    ]
