# Generated by Django 6.0.5 on 2026-05-26 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=200, verbose_name='Activity name')),
                ('activity_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Activity date')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Activity metadata')),
            ],
            options={
                'verbose_name': 'Dashboard activity',
                'verbose_name_plural': 'Dashboard activities',
                'ordering': ['-activity_date'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('message', models.TextField(verbose_name='Message')),
                ('notification_type', models.CharField(choices=[('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('quiz', 'Quiz'), ('result', 'Result')], db_index=True, default='info', max_length=20, verbose_name='Notification type')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='Read')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
